version: '3.8'

services:
  pdfly-next:
    container_name: pdfly-next
    build:
      context: .
      dockerfile: Dockerfile
    
    ports:
      - '3000:3000'
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
